services:
  database:
    image: 'postgres:15-alpine'
    container_name: 'postgres'
    ports:
      - "127.0.0.1:5432:5432"
      - "::1:5432:5432"

    environment:
      # POSTGRES_USER: username # The PostgreSQL user (useful to connect to the database)
      # POSTGRES_PASSWORD:
      POSTGRES_HOST_AUTH_METHOD: trust
      # POSTGRES_DB: default_database # The PostgreSQL default database (automatically created at first launch)
    volumes:
      - ${HOME}/data/postgresql:/var/lib/postgresql/data/
